export default 
{
    Inicio: "Home",
    Productos: "Products",
    Galeria: "Gallery",
    Sucursales: "Branches",
    pasteles: "Cakes",
    Muffins: "Muffins",
    Galletas: "Cookies",
    Postres: "Desserts",
    Contactanos: "Contact Us",
    buscas: "Are you looking for the perfect cake or a delicious dessert?",
    buscas1: "With our simple and personalized process, you can order your favorite desserts in just a few steps. Discover how to do it and enjoy a sweet and hassle-free experience.",
    INICIO1: "Pastelería América is a business specialized in crafting artisanal cakes and desserts, characterized by quality, tradition, and elegant style. We offer a variety of sweet options, perfect for celebrations and special moments, standing out for our attention to detail and exquisite flavors.",
    paso1: "Explore our menu",
    DESCRIPTION1: "Check out our variety of products: custom cakes, individual desserts, and more. Find inspiration in our gallery of flavors and decorations.",
    paso2: "Contact us or place your order online",
    DESCRIPTION2: "Order directly from our online store or contact us for inquiries and customizations. We love making your sweet ideas come true.",
    paso3: "Customize your choice",
    DESCRIPTION3: "Select flavors, sizes, and special decorations to make your cake unique. Our pastry experts will help you achieve it.",
    paso4: "Pick up or receive your order",
    DESCRIPTION4: "Stop by our store to pick up your order or take advantage of our home delivery service.",
    unico: "What makes us unique",
    WID1: "Unique and high-quality flavors",
    WID_1: "We use fresh, carefully selected ingredients to ensure the best taste in every bite.",
    WID2: "Custom designs",
    WID_2: "We offer cakes and desserts with unique decorations tailored to your tastes and special occasions.",
    WID3: "Attention to detail",
    WID_3: "Each creation is handcrafted, ensuring we meet your expectations.",
    WID4: "Reliable delivery",
    WID_4: "Receive your orders on time with our home delivery service, perfect for important events.",
    visit: "Visit us",
    testimonials: "Testimonials",
    testimonios1: "Delicious cakes made with love! From the packaging to the customer service, everything is amazing. The jellies are super tasty, not overly sweet, and full of flavor! I love Pastelería América for its homemade taste, and you can tell they put love and care into everything they make! 💕🤗🌟✨💕",
    testimonios2: "Excellent cake quality and a unique taste.",
    testimonios3: "Great service, top quality, super delicious, incredibly creative, very professional, and super friendly! I love their cakes—every single one is delicious! 🤤 Highly recommended! 🤗",
    testimonios4: "Excellent service, amazing flavors, and stunning decorations. A truly rich pastry shop!",
    testimonios5: "Best bakery in Ribera de Chapala. Don't go anywhere else!",
    testimonios6: "The cakes are delicious, they have a wide variety of products, and the decorations are beautiful.",
    FAQS: "Frequently Asked Questions",
    faqs1: "Can I customize my cake or dessert?",
    faqs_1: "Yes, definitely! You can personalize your cake or dessert with names, colors, specific themes, and even unique flavors. Just let us know your preferences when placing your order, and we will make sure your design is perfect.",
    faqs2: "How far in advance should I place my order?",
    faqs_2: "For special events like birthdays or weddings, we recommend placing your order at least 3 to 5 days in advance. If it's a large order or has intricate decorations, it's best to order at least a week ahead. The sooner, the better to ensure availability!",
    faqs3: "Do you have options for people with dietary restrictions?",
    faqs_3: "Yes, we offer options for people with various dietary restrictions. We have gluten-free, sugar-free, vegan, and dairy-free cakes. Please let us know any dietary needs when placing your order, and we will make sure to provide a delicious and safe option for you.",
    faqs4: "Do you offer home delivery?",
    faqs_4: "Yes, we offer home delivery. You can choose this option when placing your order, and we will ensure your cake or dessert arrives on time and in perfect condition at your chosen location.",
    faqs5: "What flavors and sizes are available?",
    faqs_5: "We have a variety of flavors to choose from, including vanilla, chocolate, red velvet, fruit flavors, and more. We also offer different cake sizes to meet your needs, from small cakes for family gatherings to large ones for events. Feel free to ask about our options, and we will help you find the perfect one for your occasion!",
    faqs6: "How long do cakes last, and how should I store them?",
    faqs_6: "Our cakes stay fresh for up to 3 days if stored in a cool, dry place. If they have fillings or cream, we recommend keeping them refrigerated and taking them out 30 minutes before serving for the best taste and texture.",
    PASTEL: "Cakes",
    PASTELES: "Cakes",
    PASTELES0: "Discover our most delicious and popular cakes, perfect for any occasion.",
    MUFFINS0: "Discover our delicious variety of muffins, perfect for any occasion.",
    GALLETAS0: "Enjoy our artisanal cookies, baked with the finest ingredients for an irresistible taste.",
    POSTRES0: "Enjoy our artisanal tarts, baked with the finest ingredients for an irresistible taste.",
    PASTEL1: "Vanilla Tres Leches Cake",
    PASTEL_1: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__1: "Vanilla sponge cake filled with cream and strawberry jam, soaked in milk.",
    PASTEL_2: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__2: "Fluffy sponge infused with coffee, soaked in tres leches cappuccino flavor, filled with buttercream with a touch of caramel and walnut pieces.",
    PASTEL3: "Red Velvet Cake",
    PASTEL_3: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__3: "Red chocolate sponge cake with a cream cheese filling.",
    PASTEL4: "Carrot Cake with Cream Cheese",
    PASTEL_4: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__4: "Carrot sponge cake with walnuts, pineapple, and cranberries, egg-free.",
    PASTEL___4: "Filled with cream cheese.",
    PASTEL5: "Oreo",
    PASTEL_5: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__5: "Semi-dark chocolate sponge cake filled with Oreo-flavored cream and cookie pieces.",
    PASTEL6: "Mocha",
    PASTEL_6: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__6: "Vanilla sponge soaked in coffee liqueur, filled with buttercream and walnuts.",
    PASTEL7: "Choco-Cheese",
    PASTEL_7: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__7: "American chocolate sponge cake with a soft texture, filled with cheese flan.",
    PASTEL8: "Double Chocolate",
    PASTEL_8: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__8: "Semi-dark chocolate sponge cake, soaked in syrup.",
    PASTEL___8: "Filled with chocolate cream, covered with 60% cocoa ganache.",
    PASTEL9: "Double Chocolate with Fruit",
    PASTEL_9: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__9: "Delicious chocolate sponge cake with a creamy cheesecake filling, achieving a perfect balance between sweetness and intensity.",
    PASTEL10: "Orange Cake",
    PASTEL_10: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__10: "Soft orange sponge cake with natural zest, filled with orange and cream cheese filling.",
    PASTEL11: "Choco-Flan",
    PASTEL_11: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__11: "Layers of soft vanilla flan and chocolate sponge cake in a single preparation.",
    PASTEL___11: "Topped with golden caramel for a sweet and balanced flavor.",
    PASTEL12: "Carrot Cake",
    PASTEL_12: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__12: "Carrot sponge cake with walnuts, pineapple, and cranberries, egg-free.",
    PASTEL___12: "Filled with whipped cream.",
    PASTEL13: "Choco-Vanilla",
    PASTEL_13: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__13: "Half double chocolate, half vanilla sponge cake.",
    PASTEL___13: "Filled with cream and fruit (peach, strawberry, and walnuts).",
    PASTEL14: "Mille-Feuille",
    PASTEL_14: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__14: "Layers of puff pastry filled with pastry cream, peach, strawberry, and walnuts.",
    PASTEL___14: "Topped with lemon cream.",
    PASTEL15: "Marbled Cake",
    PASTEL_15: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__15: "Vanilla sponge cake with extra-soft American chocolate.",
    PASTEL___15: "One layer filled with whipped cream, peach, and walnuts.",
    PASTEL____15: "Another layer filled with chocolate cream.",
    PASTEL16: "Fruit Cake",
    PASTEL_16: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__16: "Vanilla cake filled with fruits (peach, pineapple, strawberry, and walnuts).",
    PASTEL___16: "Soaked in syrup.",
    PASTEL17: "Cheesecake",
    PASTEL_17: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__17: "Delicious chocolate sponge cake with a creamy cheesecake filling, achieving a perfect balance between sweetness and intensity.",
    PASTEL18: "Walnut Cake",
    PASTEL_18: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__18: "Walnut-flavored sponge cake filled with cream and walnut pieces.",
    PASTEL19: "Black Forest",
    PASTEL_19: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__19: "Bitter chocolate sponge cake filled with cream and cherries.",
    PASTEL20: "Chocolate Tres Leches Cake",
    PASTEL_20: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__20: "Chocolate sponge cake soaked in three milks, filled with chocolate cream.",
    PASTEL21: "Dulce de Leche Cake",
    PASTEL_21: "Small Cake (5 people) - $200 | Medium Cake (10 people) - $300",
    PASTEL__21: "Three milks flavored sponge cake with dulce de leche in both the milk and filling.",
    PASTEL22: "Cakebox",  
    PASTEL_22: "A fluffy cake with a unique flavor.",  
    PASTEL__22: "Only available in Red Velvet or Double Chocolate flavors.",  
    PASTEL23: "Walnut Cake",  
    PASTEL_23: "A classic with a special walnut touch.",  
    PASTEL__23: "Fluffy cake with walnut pieces.",
    MUFFIN1:"Corn Muffin",
    MUFFIN_1: "A sweet and soft muffin with the authentic flavor of corn.",
    MUFFIN__1: "Made with natural corn and a touch of vanilla.",
    MUFFIN___1: "Moist texture and homemade taste.",
    MUFFIN2: "Chocolate Muffin",
    MUFFIN_2: "For chocolate lovers, with an intense flavor and fluffy texture.",
    MUFFIN__2: "Made with pure cocoa and chocolate chunks.",
    MUFFIN___2: "Perfect to pair with coffee or milk.",
    MUFFIN3: "Banana Muffin with Chocolate Chips",
    MUFFIN_3: "Fluffy and perfectly balanced between the sweetness of banana and chocolate.",
    MUFFIN__3: "Made with natural banana and semi-sweet chocolate chips.",
    MUFFIN___3: "Ideal for breakfast or snacks.",
    MUFFIN4: "Orange Muffin",  
    MUFFIN_4: "Fluffy and aromatic with a refreshing citrus touch.",  
    MUFFIN__4: "Made with natural orange zest and juice for an intense flavor.",  
    MUFFIN___4: "Ideal for breakfast or as a light and delicious snack.",  
    MUFFIN5: "Red Berries Muffin",  
    MUFFIN_5: "Soft and moist with a perfect balance of sweetness and tartness.",  
    MUFFIN__5: "Made with a mix of natural berries for a fresh and juicy bite.",  
    MUFFIN___5: "Great for a fruity and nutritious snack.",  
    MUFFIN6: "Chocolate Muffin",  
    MUFFIN_6: "Rich, moist, and intensely chocolaty.",  
    MUFFIN__6: "Made with high-quality cocoa and semi-sweet chocolate chips.",  
    MUFFIN___6: "Perfect for chocolate lovers at any time of the day.", 
    GALLETAS1: "Alfajor Cookies with Strawberry Jam",
    GALLETAS_1: "Delicious alfajor cookies filled with strawberry jam, soft with a sweet touch.",
    GALLETAS__1: "Filled with strawberry jam and dusted with powdered sugar.",
    POSTRES1: "Fruit Tart with Praline",
    POSTRES_1: "A perfect combination of smooth cream, fresh fruits, and a crunchy praline touch.",
    POSTRES__1: "Ideal for birthdays and family gatherings.",
    POSTRES2: "Lemon Curd Tart",
    POSTRES_2: "An explosion of citrus flavor with a creamy and refreshing texture.",
    POSTRES__2: "Made with fresh lemon and a crunchy cookie base.",
    POSTRES3: "Cups",
    POSTRES_3: "Small bites of crunchy dough filled with soft cream cheese.",
    POSTRES__3: "Fluffy texture with a creamy filling.",
    POSTRES___3: "Perfect to pair with coffee or tea.",
    POSTRES4: "Argentinian Alfajor",
    POSTRES_4: "A traditional sweet filled with dulce de leche.",
    POSTRES__4: "Double layer of cookie filled with dulce de leche.",
    POSTRES5: "Pastry Cream Empanadas",
    POSTRES_5: "Delicious empanadas filled with soft, sweet pastry cream.",
    POSTRES__5: "Golden, crispy dough with a soft and creamy filling.",
    POSTRES___5: "Perfect to pair with coffee or tea.",
    POSTRES6: "Pineapple and Apple Empanadas",
    POSTRES_6: "Juicy filling of pineapple and apple.",
    POSTRES__6: "Baked to achieve a golden, crunchy texture.",
    POSTRES___6: "Juicy filling of pineapple and apple.",
    POSTRES7: "Pineapple Tartlets",
    POSTRES_7: "Mini tarts with a juicy pineapple filling and a crunchy base.",
    POSTRES__7: "Cookie base with a sweet pineapple filling.",
    POSTRES8: "Mini Fruit Tart",  
    POSTRES_8: "Small tarts with a fresh and colorful fruit mix.",  
    POSTRES__8: "Crispy base with a creamy filling and a selection of fresh fruits.",  
    POSTRES9: "Truffles",  
    POSTRES_9: "Small spheres of pure chocolate with intense flavor.",
    POSTRES__9: "Delicate and soft. Available in flavors: chocolate, coconut, and walnut.",
    POSTRES10: "Mini Apple Tart",  
    POSTRES_10: "The classic apple tart flavor in a perfect size.",  
    POSTRES__10: "Caramelized apple filling with cinnamon over a golden and crispy base.",  
    POSTRES11: "Mini Walnut Tart",  
    POSTRES_11: "A crunchy bite with the unmistakable taste of walnuts.",  
    POSTRES__11: "Golden base and caramelized walnut filling with a touch of vanilla.",  
    POSTRES12: "Alfajor Box (Strawberry and Nutella)",  
    POSTRES_12: "The perfect combination of alfajores in a special presentation.",  
    POSTRES__12: "Includes alfajores filled with strawberry and Nutella, dusted with powdered sugar.",  
    POSTRES13: "Walnut Tart",  
    POSTRES_13: "The ideal balance between crunchiness and sweetness.",  
    POSTRES__13: "Buttery crust with a generous caramelized walnut filling.",  
    POSTRES14: "Butter Pound Cake",  
    POSTRES_14: "A soft and fluffy pound cake with the classic buttery touch.",  
    POSTRES__14: "Light texture and a comforting flavor that pairs perfectly with any moment of the day.",  
    POSTRES15: "Walnut Pound Cake",  
    POSTRES_15: "The perfect combination of softness and the crunchy touch of walnuts.",  
    POSTRES__15: "Moist crumb with walnut pieces that add texture and flavor.",  
    POSTRES16: "Chocolate Mousse",  
    POSTRES_16: "A light dessert with an explosion of chocolate in every spoonful.",  
    POSTRES__16: "Airy and creamy texture with the perfect balance of sweetness and intensity.",  
    POSTRES17: "Lemon Mousse",  
    POSTRES_17: "Freshness and creaminess in every bite.",  
    POSTRES__17: "Light mousse with the perfect citrus touch for a refreshing finish.",  
    POSTRES18: "Ferrero Mousse",  
    POSTRES_18: "The irresistible taste of Ferrero Rocher in a creamy dessert.",  
    POSTRES__18: "Smooth mousse with hazelnuts and chocolate for a sophisticated delight.",  
    POSTRES19: "Brownies",  
    POSTRES_19: "Pure chocolate in a dense and delicious texture.",  
    POSTRES__19: "Crunchy on the outside and moist on the inside, perfect for chocolate lovers.",  
    POSTRES20: "Custom Cupcakes",  
    POSTRES_20: "Small edible works of art, designed to your taste.",  
    POSTRES__20: "Fluffy sponge cake with unique decorations and flavors for every occasion.",  
    POSTRES21: "Orange Ring Cake",  
    POSTRES_21: "Soft and with a refreshing citrus touch.",  
    POSTRES__21: "Fluffy cake with the natural aroma and flavor of orange.",  
    POSTRES22: "Profiteroles",  
    POSTRES_22: "Small choux pastry balls filled with flavor.",  
    POSTRES__22: "Filled with pastry cream and coated with a touch of chocolate.",
    GALLETAS2: "Alfajor Cookies with Nutella",  
    GALLETAS_2: "Soft and delicate, with a creamy Nutella filling.",  
    GALLETAS__2: "Double butter cookie filled with Nutella and dusted with powdered sugar.",   
    GALLETAS3: "Big Cookies",  
    GALLETAS_3: "Large, flavorful cookies, perfect for the sweet-toothed.",  
    GALLETAS__3: "Available in three options: oatmeal, chocolate chips, or nuts, each with its own unique flavor and texture.",  
    GALLETAS4: "Assorted Box",  
    GALLETAS_4: "A special selection of our best cookies in one box.",  
    GALLETAS__4: "Includes a variety of butter, chocolate, nut, and more cookies.",  
    GALLETAS5: "Centenario Cookies",  
    GALLETAS_5: "Traditional cookies with a special touch and unmistakable flavor.",  
    GALLETAS__5: "Soft cookies with a jam center and a shiny glaze for a sweet and delicate finish.",  
    GALLETAS6: "Nut Kisses",  
    GALLETAS_6: "Small and soft, with a delicate nut flavor and a touch of sweetness.",  
    GALLETAS__6: "Butter cookies with ground nuts, dusted with powdered sugar.",  
    GALLETAS7: "Sugar-Free Cookie",  
    GALLETAS_7: "A healthy, sugar-free option, but with a delicious taste.",  
    GALLETAS__7: "Naturally sweetened and made with quality ingredients for a light and tasty bite.",
    GALLETAS8: "Mini Nutella-filled Cookie",  
    GALLETAS_8: "A small bite, but full of pleasure.",  
    GALLETAS__8: "Delicious small cookies with a creamy Nutella filling.",
    galeriade: "Dessert Gallery",
    galeriades: "Delicious desserts for every occasion",    
    nuestros_videos: "Our Videos",  
    explora: "Explore more with us.",
    videotitle1: "Techniques",  
    videodes1: "Piping and nozzle decoration technique.",
    videotitle2: "This is how our cakes are made",  
    videodes2: "The art behind every bite.",  
    videotitle3: "Cake and coffee: a sweet visit",  
    videodes3: "Flavor and unforgettable moments.",  
    blog1: "Welcome to Our Pastry Blog"  ,
    blog: "If you are a baking lover, this is the perfect place for you. In our blog, you will find delicious recipes, baking techniques, cake decorating tips, and common mistakes to avoid. Whether you're a beginner looking to bake your first cake or an expert",
    publicaciones: "Related Posts",  
    todaspublicaciones: "View All Posts",
    horario: "Schedule",
    ubicacion: "Location",
    pedidos: "Connect with us",
    pedidos1: "For orders, quotes, or any inquiries, we are just a click away.",
    sucursalchapala: "Chapala Branch",
    sucursalchapalasubtitle: "Located in the heart of Chapala, our branch offers a cozy atmosphere where you can enjoy our exquisite cakes and handcrafted desserts. With an incredible view and a comfortable space, it's the perfect place to share sweet moments with your loved ones.",
    sucursalajijic: "Ajijic Branch",
    sucursalajijicsubtitle: "Located in the picturesque town of Ajijic, our branch combines the charm of the lake with the sweet taste of our desserts. Enjoy a relaxed and cozy atmosphere while savoring our freshly baked specialties. A perfect place to treat yourself!",
    sucursaljoco: "Jocotepec Branch",
    sucursaljocosubtitle: "In the beautiful region of Jocotepec, our bakery offers you a warm space where every bite is a delight. Whether it's for a morning coffee or a cake for a special occasion, here you'll find the perfect combination of flavor and quality.",
    horachapala1: "Monday - Saturday 9 a.m - 9 p.m",
    horachapala2: "Sunday 9 a.m - 8 p.m",
    horajoco1: "Monday - Saturday 9 a.m. - 6 p.m.",
    horajoco2: "Sunday Closed",
    horaajijic1: "Monday - Saturday 8:30 a.m. - 9 p.m.",
    horaajijic2: "Sunday 8:30 a.m. - 7 p.m."


}
