export default 
{
    Inicio: "Home",
    Productos: "Products",
    Galeria: "Gallery",
    test: "Cakes",
    caca: "Muffins",
    mierda: "Cookies",
    Contactanos: "Contact Us",
    buscas: "Are you looking for the perfect cake or a delicious dessert?",
    buscas1: "With our simple and personalized process, you can order your favorite desserts in just a few steps. Discover how to do it and enjoy a sweet and hassle-free experience.",
    INICIO1: "Pastelería América is a business specialized in crafting artisanal cakes and desserts, characterized by quality, tradition, and elegant style. We offer a variety of sweet options, perfect for celebrations and special moments, standing out for our attention to detail and exquisite flavors.",
    title1: "Explore our menu",
    DESCRIPTION1: "Check out our variety of products: custom cakes, individual desserts, and more. Find inspiration in our gallery of flavors and decorations.",
    title2: "Contact us or place your order online",
    DESCRIPTION2: "Order directly from our online store or contact us for inquiries and customizations. We love making your sweet ideas come true.",
    title3: "Customize your choice",
    DESCRIPTION3: "Select flavors, sizes, and special decorations to make your cake unique. Our pastry experts will help you achieve it.",
    title4: "Pick up or receive your order",
    DESCRIPTION4: "Stop by our store to pick up your order or take advantage of our home delivery service.",
    PITO: "What makes us unique",
    WID1: "Unique and high-quality flavors",
    WID_1: "We use fresh, carefully selected ingredients to ensure the best taste in every bite.",
    WID2: "Custom designs",
    WID_2: "We offer cakes and desserts with unique decorations tailored to your tastes and special occasions.",
    WID3: "Attention to detail",
    WID_3: "Each creation is handcrafted, ensuring we meet your expectations.",
    WID4: "Reliable delivery",
    WID_4: "Receive your orders on time with our home delivery service, perfect for important events.",
    visit: "Visit us",
    testimonials: "Testimonials",
    testi1: "Delicious cakes made with love! From the packaging to the customer service, everything is amazing. The jellies are super tasty, not overly sweet, and full of flavor! I love Pastelería América for its homemade taste, and you can tell they put love and care into everything they make! 💕🤗🌟✨💕",
    testi2: "Excellent cake quality and a unique taste.",
    testi3: "Great service, top quality, super delicious, incredibly creative, very professional, and super friendly! I love their cakes—every single one is delicious! 🤤 Highly recommended! 🤗",
    testi4: "Excellent service, amazing flavors, and stunning decorations. A truly rich pastry shop!",
    testi5: "Best bakery in Ribera de Chapala. Don't go anywhere else!",
    testi6: "The cakes are delicious, they have a wide variety of products, and the decorations are beautiful.",
    FAQS: "Frequently Asked Questions",
    faqs1: "Can I customize my cake or dessert?",
    faqs_1: "Yes, definitely! You can personalize your cake or dessert with names, colors, specific themes, and even unique flavors. Just let us know your preferences when placing your order, and we will make sure your design is perfect.",
    faqs2: "How far in advance should I place my order?",
    faqs_2: "For special events like birthdays or weddings, we recommend placing your order at least 3 to 5 days in advance. If it's a large order or has intricate decorations, it's best to order at least a week ahead. The sooner, the better to ensure availability!",
    faqs3: "Do you have options for people with dietary restrictions?",
    faqs_3: "Yes, we offer options for people with various dietary restrictions. We have gluten-free, sugar-free, vegan, and dairy-free cakes. Please let us know any dietary needs when placing your order, and we will make sure to provide a delicious and safe option for you.",
    faqs4: "Do you offer home delivery?",
    faqs_4: "Yes, we offer home delivery. You can choose this option when placing your order, and we will ensure your cake or dessert arrives on time and in perfect condition at your chosen location.",
    faqs5: "What flavors and sizes are available?",
    faqs_5: "We have a variety of flavors to choose from, including vanilla, chocolate, red velvet, fruit flavors, and more. We also offer different cake sizes to meet your needs, from small cakes for family gatherings to large ones for events. Feel free to ask about our options, and we will help you find the perfect one for your occasion!",
    faqs6: "How long do cakes last, and how should I store them?",
    faqs_6: "Our cakes stay fresh for up to 3 days if stored in a cool, dry place. If they have fillings or cream, we recommend keeping them refrigerated and taking them out 30 minutes before serving for the best taste and texture.",
    PASTEL: "Cakes",
    PASTELES: "Cakes",
    PASTELES0: "Discover our most delicious and popular cakes, perfect for any occasion.",
    PASTEL1: "Vanilla Tres Leches Cake",
    PASTEL_1: "A classic favorite, soft and delicious, with a touch of cream and fruits.",
    PASTEL__1: "Vanilla sponge cake filled with cream and strawberry jam, soaked in milk.",
    PASTEL_2: "An exquisite cake with the perfect balance between coffee and sweetness.",
    PASTEL__2: "Fluffy sponge infused with coffee, soaked in tres leches cappuccino flavor, filled with buttercream with a touch of caramel and walnut pieces.",
    PASTEL3: "Red Velvet Cake",
    PASTEL_3: "An elegant cake with a smooth taste and a touch of cream cheese.",
    PASTEL__3: "Red chocolate sponge cake with a cream cheese filling.",
    PASTEL4: "Carrot Cake with Cream Cheese",
    PASTEL_4: "An irresistible classic with the softness of carrot, aromatic spices, and a touch of walnut.",
    PASTEL__4: "Carrot sponge cake with walnuts, pineapple, and cranberries, egg-free.",
    PASTEL___4: "Filled with cream cheese.",
    PASTEL5: "Oreo",
    PASTEL_5: "An irresistible cake with the classic combination of chocolate and cookies.",
    PASTEL__5: "Semi-dark chocolate sponge cake filled with Oreo-flavored cream and cookie pieces.",
    PASTEL6: "Mocha",
    PASTEL_6: "A cake with the intensity of coffee and the perfect sweetness for mocha lovers.",
    PASTEL__6: "Vanilla sponge soaked in coffee liqueur, filled with buttercream and walnuts.",
    PASTEL7: "Choco-Cheese",
    PASTEL_7: "The perfect fusion between intense chocolate and the smoothness of cream cheese.",
    PASTEL__7: "American chocolate sponge cake with a soft texture, filled with cheese flan.",
    PASTEL8: "Double Chocolate",
    PASTEL_8: "The perfect blend of intense chocolate and cream cheese smoothness.",
    PASTEL__8: "Semi-dark chocolate sponge cake, soaked in syrup.",
    PASTEL___8: "Filled with chocolate cream, covered with 60% cocoa ganache.",
    PASTEL9: "Double Chocolate with Fruit",
    PASTEL_9: "The perfect fusion between intense chocolate and cheesecake smoothness.",
    PASTEL__9: "Delicious chocolate sponge cake with a creamy cheesecake filling, achieving a perfect balance between sweetness and intensity.",
    PASTEL10: "Orange Cake",
    PASTEL_10: "A fluffy cake with a refreshing citrus touch.",
    PASTEL__10: "Soft orange sponge cake with natural zest, filled with orange and cream cheese filling.",
    PASTEL11: "Choco-Flan",
    PASTEL_11: "The perfect combination of creamy flan and chocolate sponge cake.",
    PASTEL__11: "Layers of soft vanilla flan and chocolate sponge cake in a single preparation.",
    PASTEL___11: "Topped with golden caramel for a sweet and balanced flavor.",
    PASTEL____11: "Creamy and fluffy texture in every bite.",
    PASTEL12: "Carrot Cake",
    PASTEL_12: "An exquisite cake with the perfect balance between coffee and sweetness.",
    PASTEL__12: "Carrot sponge cake with walnuts, pineapple, and cranberries, egg-free.",
    PASTEL___12: "Filled with whipped cream.",
    PASTEL13: "Choco-Vanilla",
    PASTEL_13: "The perfect balance between intense chocolate and smooth vanilla.",
    PASTEL__13: "Half double chocolate, half vanilla sponge cake.",
    PASTEL___13: "Filled with cream and fruit (peach, strawberry, and walnuts).",
    PASTEL14: "Mille-Feuille",
    PASTEL_14: "A classic pastry with delicate layers and a delicious creamy filling.",
    PASTEL__14: "Layers of puff pastry filled with pastry cream, peach, strawberry, and walnuts.",
    PASTEL___14: "Topped with lemon cream.",
    PASTEL15: "Marbled Cake",
    PASTEL_15: "A classic cake with a rich combination of vanilla and chocolate.",
    PASTEL__15: "Vanilla sponge cake with extra-soft American chocolate.",
    PASTEL___15: "One layer filled with whipped cream, peach, and walnuts.",
    PASTEL____15: "Another layer filled with chocolate cream.",
    PASTEL16: "Fruit Cake",
    PASTEL_16: "A fresh and light cake with a delicious combination of natural fruits.",
    PASTEL__16: "Vanilla cake filled with fruits (peach, pineapple, strawberry, and walnuts).",
    PASTEL___16: "Soaked in syrup.",
    PASTEL17: "Cheesecake",
    PASTEL_17: "The perfect fusion between intense chocolate and the smoothness of cream cheese.",
    PASTEL__17: "Delicious chocolate sponge cake with a creamy cheesecake filling, achieving a perfect balance between sweetness and intensity.",
    PASTEL18: "Walnut Cake",
    PASTEL_18: "A soft and fluffy cake with the unmistakable taste of walnuts.",
    PASTEL__18: "Walnut-flavored sponge cake filled with cream and walnut pieces.",
    PASTEL19: "Black Forest",
    PASTEL_19: "A classic cake with the perfect combination of chocolate and cherries.",
    PASTEL__19: "Bitter chocolate sponge cake filled with cream and cherries.",
    PASTEL20: "Chocolate Tres Leches Cake",
    PASTEL_20: "An irresistible version of the classic tres leches, with the intense flavor of chocolate.",
    PASTEL__20: "Chocolate sponge cake soaked in three milks, filled with chocolate cream.",
    PASTEL21: "Dulce de Leche Cake",
    PASTEL_21: "A creamy and delicious cake with the unmistakable flavor of dulce de leche.",
    PASTEL__21: "Three milks flavored sponge cake with dulce de leche in both the milk and filling.",
    galeriade: "Dessert Gallery",
    galeriades: "Delicious desserts for every occasion",    
    nv: "Our Videos",  
    nve: "Explore more with us.",
    videotitle1: "Techniques",  
    videodes1: "Piping and nozzle decoration technique.",
    videotitle2: "This is how our cakes are made",  
    videodes2: "The art behind every bite.",  
    videotitle3: "Cake and coffee: a sweet visit",  
    videodes3: "Flavor and unforgettable moments.",  
    blog1: "Welcome to Our Pastry Blog"  ,
    blog: "If you are a baking lover, this is the perfect place for you. In our blog, you will find delicious recipes, baking techniques, cake decorating tips, and common mistakes to avoid. Whether you're a beginner looking to bake your first cake or an expert",
    publicaciones: "Related Posts",  
    todas: "View All Posts"  


}
