export default
 {
    Inicio: "Inicio",
    Productos: "Productos",
    Galeria: "Galeria",
    Sucursales: "Sucursales",
    pasteles: "Pasteles",
    Muffins: "Progres PT",
    Galletas: "Galletas",
    Postres: "Postres",
    Contactanos: "Contáctanos",
    buscas: "En Progress PT Medical Group ofrecemos",
    buscas1: "Confía en nosotros para brindarte la atención que mereces y el cuidado que necesitas.",
    INICIO1: "En nuestra clínica de fisioterapia, nos dedicamos a mejorar tu calidad de vida a través de tratamientos personalizados y tecnología avanzada. Nuestro equipo de profesionales altamente capacitados está comprometido con ayudarte a recuperar tu movilidad, aliviar el dolor y alcanzar tus objetivos de salud.",
    paso1: "Terapia Física Personalizada",
    DESCRIPTION1: "Tratamientos diseñados a la medida de tus necesidades, enfocados en la recuperación de lesiones, mejora de la movilidad y fortalecimiento muscular.",
    paso2: "Rehabilitación Deportiva",
    DESCRIPTION2: "Programas especializados para atletas que buscan recuperarse de lesiones, prevenir futuras lesiones y optimizar su rendimiento físico.",
    paso3: "Manejo del Dolor",
    DESCRIPTION3: "Técnicas avanzadas para reducir el dolor crónico, mejorar la funcionalidad general y promover la calidad de vida.",
    paso4: "Fisioterapia Postoperatoria",
    DESCRIPTION4: "Recuperación optimizada para cirugías ortopédicas y procedimientos relacionados, asegurando una rehabilitación segura y eficiente.",
    paso5: "Terapia Manual",
    DESCRIPTION5: "Técnicas manuales que incluyen masajes terapéuticos, movilización de tejidos blandos y manipulación articular para aliviar el dolor, mejorar la movilidad y restaurar la función.",
    paso6: "Terapia de Movimiento",
    DESCRIPTION6: "Ejercicios y técnicas especializadas para mejorar la movilidad, la funcionalidad y la coordinación motora, promoviendo un bienestar físico integral.",
    unico: "Lo que nos hace únicos en Progress PT Medical Group",
    WID1: "Enfoque Personalizado",
    WID_1: "Desarrollamos tratamientos a medida, enfocados en tus necesidades y objetivos específicos, asegurando un proceso de recuperación eficiente y seguro. ",
    WID2: "Tecnología Avanzada",
    WID_2: "Utilizamos las técnicas más modernas y equipos de última generación para ofrecerte un tratamiento de la más alta calidad.",
    WID3: "Profesionales Altamente Capacitados",
    WID_3: "Nuestro equipo está compuesto por expertos en fisioterapia comprometidos con ofrecerte la mejor atención posible.",
    WID4: "Atención Integral",
    WID_4: "Ofrecemos un servicio continuo que incluye evaluación, tratamiento y seguimiento personalizado para garantizar tu bienestar.",
    visit: "Visítanos",
    testimonials: "Testimonios",
    testimonios2: "¡Experiencia excepcional en la Clínica! Recientemente tuve la oportunidad de recibir tratamiento en Progress PT y quedé impresionado por la calidad de atención y profesionalismo que experimenté. Desde el momento en que entré por la puerta, me sentí bienvenido y cuidado por el personal altamente capacitado.Lo que más me impactó fue la atención personalizada que recibí. El fisio demostró un profundo conocimiento y comprensión de mi condición, y diseño un plan de tratamiento a medida que abordó mis necesidades específicas. Cada sesión se llevó a cabo con precisión y cuidado, siempre enfocados en mi bienestar y progreso.",
    testimonios1: "Excelentes instalaciones. El fisioterapeuta ha atendido a mi familia y a mi pareja y les ha dado excelente cuidado y seguimiento. Muy recomendado.",
    testimonios3: "Excelentes instalaciones y muy buen servicio tanto de fisioterapia como de odontología.",
    testimonios4: "Excelente atención, instalaciones muy completas.",
    testimonios5: "Excelente atencion! Muy recomendado, el personal muy amable y profesional en su trabajo y las instalaciones muy limpias.",
    testimonios6: "El lugar muy limpio y el personal muy amable.",
    FAQS: "Preguntas Frecuentes",
    faqs1: "¿Cuál es el costo de las sesiones de fisioterapia? ",
    faqs_1: "El costo puede variar según la complejidad del tratamiento y la cantidad de sesiones requeridas. Para un presupuesto preciso, te invitamos a contactarnos y brindarnos más detalles sobre tus necesidades específicas.",
    faqs2: "¿Necesito una referencia médica para recibir tratamiento?",
    faqs_2: "En general, no se requiere una referencia médica. Sin embargo, algunos seguros pueden solicitarla. Te recomendamos que consultes con tu proveedor de seguros para confirmar.",
    faqs3: "¿Tienen opciones para personas con restricciones alimenticias?",
    faqs_3: "Sí, ofrecemos opciones para personas con diversas restricciones alimenticias. Tenemos pasteles sin gluten, sin azúcar, veganos y sin lácteos. Por favor, indícanos cualquier restricción al realizar tu pedido y nos aseguraremos de ofrecerte una opción deliciosa y segura.",
    faqs4: "¿Ofrecen servicio de entrega a domicilio?",
    faqs_4: "Sí, ofrecemos servicio de entrega a domicilio. Puedes optar por esta opción al hacer tu pedido, y nos aseguraremos de que tu pastel o postre llegue a tiempo y en perfecto estado, directamente a la ubicación que elijas.",
    faqs5: "¿Cuáles son los sabores y tamaños disponibles?",
    faqs_5: "Tenemos una variedad de sabores para elegir, incluyendo vainilla, chocolate, red velvet, frutas y más. Además, ofrecemos diferentes tamaños de pasteles según tus necesidades, desde pequeños para reuniones familiares hasta grandes para eventos. ¡No dudes en preguntar por nuestras opciones y nos aseguraremos de que encuentres la perfecta para tu ocasión!",
    faqs6: "¿Cuánto tiempo duran los pasteles y cómo debo almacenarlos?",
    faqs_6: "Nuestros pasteles se mantienen frescos hasta 3 días si se conservan en un lugar fresco y seco. Si tienen rellenos o crema, recomendamos guardarlos en el refrigerador y sacarlos 30 minutos antes de servir para disfrutar su mejor sabor y textura.",
    PASTELES: "Pasteles",
    PASTELES0: "Descubre nuestros pasteles más deliciosos y populares, ideales para cualquier ocasión.",
    MUFFINS0: "Servicios de Fisioterapia de Alta Calidad en Progress PT Medical Group",
    GALLETAS0: "Disfruta de nuestras galletas artesanales, horneadas con los mejores ingredientes para un sabor irresistible.",
    POSTRES0: "Disfruta de nuestras tartas artesanales, horneadas con los mejores ingredientes para un sabor irresistible.",
    PASTEL1: "Pastel de Tres Leches Vainilla",
    PASTEL_1: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__1: "Pan de vainilla relleno de crema y mermelada de fresa bañado en leche.",
    PASTEL_2: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__2: "Bizcocho esponjoso infusionado con café, bañado en tres leches sabor capuccino y relleno de crema de mantequilla con un toque de caramelo y trozos de nuez.",
    PASTEL3: "Pastel Red Velvet",
    PASTEL_3: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__3: "Pan de chocolate rojo con relleno de crema de queso.",
    PASTEL4: "Pastel de Zanahoria con crema de Queso",
    PASTEL_4: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__4: "Pan de zanahoria con nuez, piña y arandanos, libre de huevo",
    PASTEL___4: "Relleno de crema de queso.",
    PASTEL5: "Oreo",
    PASTEL_5: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__5: "Pan de chocolate semi amargo relleno con crema sabor a oreo y galleta.",
    PASTEL6: "Moka",
    PASTEL_6: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__6: "Pan de vainilla bañado en licor de café, relleno de crema de mantequilla y nuez.",
    PASTEL7: "Chocoqueso",
    PASTEL_7: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__7: "Pan de chocolate americano. Suave con relleno de flan de queso.",
    PASTEL8: "Doble Chocolate",
    PASTEL_8: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__8: "Pan de chocolate semi amargo, bañado en Jarabe.",
    PASTEL___8: "Relleno en crema de chocolate, cubierto con ganashe al 60% de cacao.",
    PASTEL9: "Doble Chocolate con Fruta",
    PASTEL_9: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__9: "Delicioso bizcocho de chocolate con un cremoso relleno de cheesecake, logrando un balance perfecto entre dulzura e intensidad.",
    PASTEL10: "Pastel de Naranja",
    PASTEL_10: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__10: "Pan suave de naranja con rayadura natural, relleno de crema de naranja y queso.",
    PASTEL11: "Chocoflan",
    PASTEL_11: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__11: "Capas de suave flan de vainilla y bizcocho de chocolate en una sola preparación.",
    PASTEL___11: "Bañado en caramelo dorado para un sabor dulce y equilibrado.",
    PASTEL____11: "Textura cremosa y esponjosa en cada bocado.",
    PASTEL12: "Pastel de Zanahoria",
    PASTEL_12: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__12: "Pan de zanahoria con nuez, piña y arandano y libre de huevo.",
    PASTEL___12: "Relleno con crema de nata.",
    PASTEL13: "Chocovainilla",
    PASTEL_13: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__13: "Mitad de doble chocolate y mitad de pan de vainilla.",
    PASTEL___13: "Relleno de crema y fruta (durazno, fresa y nuez).",
    PASTEL14: "Mil Hojas",
    PASTEL_14: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__14: "Capas de pan de hojaldre, relleno con crema pastelera, durazno, fresa y nuez.",
    PASTEL___14: "Cubierto con crema de limón.",
    PASTEL15: "Marmoleado",
    PASTEL_15: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__15: "Pan de vainilla con chocolate americano extra suave.",
    PASTEL___15: "Con una capa rellena de crema de nata, durazno y nuez.",
    PASTEL____15: "Con una capa de relleno de crema de chocolate.",
    PASTEL16: "Pastel de Frutas",
    PASTEL_16: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__16: "Pastel de vainilla, relleno de frutas /durazno, piña, fresa y nuez).",
    PASTEL___16: "Bañado en Jarabe.",
    PASTEL17: "Cheesecake",
    PASTEL_17: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__17: "Delicioso bizcocho de chocolate con un cremoso relleno de cheesecake, logrando un balance perfecto entre dulzura e intensidad.",
    PASTEL18: "Pastel de Nuez",
    PASTEL_18: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__18: "Pan sabor a nuez, con relleno de crema y trozos de nuez.",
    PASTEL19: "Selva Negra",
    PASTEL_19: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__19: "Pan de chocolate amargo, con relleno de crema y cereza.",
    PASTEL20: "Pastel de Tres Leches Chocolate",
    PASTEL_20: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__20: "Pan de chocolate bañado en 3 leches, con relleno de crema de chocolate.",
    PASTEL21: "Pastel de Dulce de Leche",
    PASTEL_21: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__21: "Pan sabor a tres leches, con dulce de leche, en la leche y en el relleno.",
    PASTEL22: "Cakebox",
    PASTEL_22: "Un pastel esponjoso con un sabor único.",
    PASTEL__22: "Solo disponible en sabores Red Velvet o Doble Chocolate.",
    PASTEL23: "Pastel de Nuez",  
    PASTEL_23: "Un clásico con el toque especial de nuez.",  
    PASTEL__23: "Pastel esponjoso con trozos de nuez." ,
    MUFFIN1: "Terapia Física Personalizada",
    MUFFIN_1:"Evaluación y tratamiento personalizado para mejorar la movilidad y aliviar el dolor.",
    MUFFIN__1:"Realizado por profesionales capacitados con técnicas avanzadas.",
    MUFFIN___1:"Ideal para rehabilitación post-operatoria o lesiones deportivas.",
    MUFFIN2: "Cámara Hiperbárica",
    MUFFIN_2:"Terapia avanzada con oxígeno puro en un ambiente de alta presión para acelerar la recuperación.",
    MUFFIN__2:"Ideal para tratamientos post-operatorios, lesiones deportivas y condiciones neurológicas.",
    MUFFIN___2:"Mejora la cicatrización de heridas, alivia dolores crónicos y promueve la regeneración de tejidos.",
    MUFFIN3: "Alberca para Rehabilitación",
    MUFFIN_3:"Terapia acuática especializada para mejorar la movilidad, fuerza y flexibilidad.",
    MUFFIN__3:"Proporciona un ambiente de bajo impacto ideal para pacientes con dolor articular o movilidad reducida.",
    MUFFIN___3:"Beneficioso para la recuperación post-cirugía, lesiones deportivas y tratamiento de condiciones crónicas.",
    MUFFIN4: "Terapia de Rehabilitación Integral",  
    MUFFIN_4: "Programa integral para mejorar la calidad de vida y restaurar la funcionalidad física.",    
    MUFFIN__4: "Incluye evaluación completa, ejercicios terapéuticos y técnicas avanzadas.",  
    MUFFIN___4: "Ideal para pacientes con múltiples afecciones o necesidades complejas.",  
    MUFFIN5: "Sauna Terapéutico",  
    MUFFIN_5: "Terapia con calor para la relajación muscular, mejora de la circulación y alivio del estrés.",  
    MUFFIN__5: "Ideal para complementar otros tratamientos de fisioterapia y promover la recuperación física.",  
    MUFFIN___5: "Beneficioso para reducir tensiones musculares y mejorar la flexibilidad.",  
    MUFFIN6: "Rehabilitación Deportiva",  
    MUFFIN_6: "Programa específico para recuperar la movilidad y fuerza tras lesiones deportivas.",  
    MUFFIN__6: "Diseñado para atletas de todos los niveles.",  
    MUFFIN___6: "Se enfoca en ejercicios funcionales y recuperación progresiva."  ,
    GALLETAS1: "Galletas de alfajor con mermelada de fresa",
    GALLETAS_1: "Deliciosas galletas rellenas de mermelada de fresa, con una textura suave y un toque dulce.",
    GALLETAS__1: "Rellenas de mermelada de fresa y espolvoreadas con azúcar glass.",
    GALLETAS2: "Galletas de Alfajor con Nutella",  
    GALLETAS_2: "Suaves y delicadas, con un relleno cremoso de Nutella.",  
    GALLETAS__2: "Doble galleta de mantequilla rellena de Nutella y espolvoreada con azúcar glass.",   
    GALLETAS3: "Galletones",  
    GALLETAS_3: "Galletas grandes y llenas de sabor, ideales para los más golosos.",  
    GALLETAS__3: "Disponibles en tres opciones: avena, chispas de chocolate o nuez, cada una con su propio sabor y textura única.",
    GALLETAS4: "Caja Surtida",  
    GALLETAS_4: "Una selección especial de nuestras mejores galletas en una sola caja.",  
    GALLETAS__4: "Incluye una variedad de galletas de mantequilla, chocolate, nuez y más.",  
    GALLETAS5: "Galletas Centenario",  
    GALLETAS_5: "Galletas tradicionales con un toque especial y un sabor inconfundible.",  
    GALLETAS__5: "Galletas suaves con un centro de mermelada y un glaseado brillante para un acabado dulce y delicado.",
    GALLETAS6: "Besitos de Nuez",  
    GALLETAS_6: "Pequeñas y suaves, con un delicado sabor a nuez y un toque de dulzura.",  
    GALLETAS__6: "Galletas de mantequilla con nuez molida y espolvoreadas con azúcar glass.",  
    GALLETAS7: "Galleta sin Azúcar",  
    GALLETAS_7: "Una opción saludable sin azúcar, pero con un sabor delicioso.",  
    GALLETAS__7: "Endulzada naturalmente y elaborada con ingredientes de calidad para un bocado ligero y sabroso.",   
    GALLETAS8: "Mini Galleta rellena de Nutella",  
    GALLETAS_8: "Un bocado pequeño, pero lleno de placer.",  
    GALLETAS__8: "Deliciosas galletas pequeñas con un relleno de Nutella cremoso",         
    POSTRES1: "Tarta de frutas con praliné",
    POSTRES_1: "Una combinación perfecta de crema suave, frutas frescas y un toque crujiente de praliné.",
    POSTRES__1: "Ideal para cumpleaños y reuniones familiares.",
    POSTRES2: "Tarta de curd de limón",
    POSTRES_2: "Una explosión de sabor cítrico con una textura cremosa y refrescante.",
    POSTRES__2: "Elaborada con limón fresco y base de galleta crujiente.",
    POSTRES3: "Cubiletes",
    POSTRES_3: "Pequeños bocados de masa crujiente rellenos de una suave crema de queso.",
    POSTRES__3: "Textura esponjosa con un relleno cremoso.",
    POSTRES___3: "Perfecto para acompañar con café o té.",
    POSTRES4: "Alfajor Argentino",
    POSTRES_4: "Un dulce tradicional con relleno de dulce de leche.",
    POSTRES__4: "Doble capa de galleta rellena de dulce de leche.",
    POSTRES5: "Empanadas de crema pastelera",
    POSTRES_5: "Deliciosas empanadas rellenas de crema pastelera suave y dulce.",
    POSTRES__5: "Masa dorada y crujiente con un relleno suave y cremoso.",
    POSTRES___5: "Perfectas para acompañar con café o té.",
    POSTRES6: "Empanadas de piña y manzana",
    POSTRES_6: "Relleno jugoso de piña y manzana.",
    POSTRES__6: "Horneadas hasta lograr una textura dorada y crujiente.",
    POSTRES___6: "Relleno jugoso de piña y manzana.",
    POSTRES7: "Tartitas de piña",
    POSTRES_7: "Mini tartas con un relleno jugoso de piña y una base crujiente.",
    POSTRES__7: "Base de galleta con un relleno dulce de piña.",
    POSTRES8: "Mini Tarta de Frutas",
    POSTRES_8: "Pequeñas tartas con una mezcla fresca y colorida de frutas.",
    POSTRES__8: "Base crujiente con un relleno cremoso y una selección de frutas frescas.",
    POSTRES9: "Trufas",
    POSTRES_9: "Pequeñas esferas de puro chocolate y sabor intenso.",
    POSTRES__9: "Delicadas y suaves. Disponibles en sabores: chocolate, coco y nuez.",
    POSTRES10: "Mini Tarta de Manzana",
    POSTRES_10: "El clásico sabor de la tarta de manzana en un tamaño perfecto.",
    POSTRES__10: "Relleno de manzana caramelizada con canela sobre una base dorada y crujiente.",
    POSTRES11: "Mini Tarta de Nuez",
    POSTRES_11: "Un bocado crujiente con el inconfundible sabor de la nuez.",
    POSTRES__11: "Base dorada y relleno de nuez caramelizada con un toque de vainilla.",
    POSTRES12: "Caja de alfajor (fresa y Nutella)",
    POSTRES_12: "La combinación perfecta de alfajores en una presentación especial.",
    POSTRES__12: "Incluye alfajores rellenos de fresa y Nutella, espolvoreados con azúcar glass.",
    POSTRES13: "Tarta de Nuez",
    POSTRES_13: "El equilibrio ideal entre lo crujiente y lo dulce.",
    POSTRES__13: "Masa quebradiza con un relleno generoso de nuez caramelizada.",
    POSTRES14: "Panqué de Mantequilla",
    POSTRES_14: "Un panqué suave y esponjoso con el toque clásico de la mantequilla.",
    POSTRES__14: "Textura ligera y un sabor reconfortante que acompaña cualquier momento del día.",
    POSTRES15: "Panqué de Nuez",
    POSTRES_15: "La combinación perfecta entre suavidad y el toque crujiente de la nuez.",
    POSTRES__15: "Miga esponjosa con trozos de nuez que aportan textura y sabor.",
    POSTRES16: "Mousse de Chocolate",
    POSTRES_16: "Un postre ligero con una explosión de chocolate en cada cucharada.",
    POSTRES__16: "Textura aireada y cremosa con el balance perfecto de dulzura e intensidad.",
    POSTRES17: "Mousse de Limón",
    POSTRES_17: "Frescura y cremosidad en cada bocado.",
    POSTRES__17: "Mousse ligero con el toque cítrico perfecto para un final refrescante.",
    POSTRES18: "Mousse de Ferrero",
    POSTRES_18: "El sabor irresistible del Ferrero Rocher en un postre cremoso.",
    POSTRES__18: "Mousse suave con avellanas y chocolate para un deleite sofisticado.",
    POSTRES19: "Brownies",
    POSTRES_19: "Puro chocolate en una textura densa y deliciosa.",
    POSTRES__19: "Crujiente por fuera y húmedo por dentro, perfecto para los amantes del chocolate.",
    POSTRES20: "Cupcakes Personalizados",
    POSTRES_20: "Pequeñas obras de arte comestibles, diseñadas a tu gusto.",
    POSTRES__20: "Bizcocho esponjoso con decoraciones y sabores únicos para cada ocasión.",
    POSTRES21: "Rosca de Naranja",
    POSTRES_21: "Esponjosa y con un toque cítrico refrescante.",
    POSTRES__21: "Suave bizcocho con el aroma y sabor natural de la naranja.",
    POSTRES22: "Profiteroles",
    POSTRES_22: "Pequeñas bolitas de pasta choux rellenas de sabor.",
    POSTRES__22: "Rellenas de crema pastelera y bañadas con un toque de chocolate.",  
    galeriade: "Galería de fotos de Progress PT Medical Group",
    galeriades: "Conoce mejor nuestras instalaciones y descubre el ambiente acogedor y profesional que te espera en Progress PT Medical Group.",
    nuestros_videos: "Nuestros Videos",
    explora: "Explora más con nosotros.",
    videotitle1: "Técnicas",
    videodes1: "Técnica en decoracion con duyas o boquillas.",
    videotitle2: "Así nacen nuestros pasteles",
    videodes2: "El arte detrás de cada bocado.",
    videotitle3: "Pastel y café: una dulce visita",
    videodes3:"Sabor y momentos inolvidables.",
    blog1: "Bienvenido al Blog de Progres PT",       
    blog: "Si te interesa mejorar tu salud física y bienestar, este es el lugar perfecto para ti. En nuestro blog de Progres PT encontrarás contenido sobre las últimas técnicas en fisioterapia, consejos para optimizar tu recuperación, tratamientos innovadores para diversas condiciones físicas y casos de éxito que te inspirarán a alcanzar tu máximo potencial.",
    publicaciones: "Publicaciones Relacionadas",
    todaspublicaciones: "Ver Todas las Publicaciones ",
    horario: "Horario",
    ubicacion: "Ubicación",
    pedidos: "Conéctate con nosotros",
    pedidos1: "Para pedidos, cotizaciones o cualquier consulta, estamos a un clic de distancia.",
    apps:"¿Qué es una app?",
    appssubtitle:"Una aplicación (App) es un software diseñado especialmente para dispositivos móviles, como smartphones y tablets (iOS y Android), ofreciendo una experiencia de usuario fluida y óptima, tomando máximo provecho de las capacidades de los dispositivos. Son interactivas y pueden cumplir una variedad de propósitos, desde proporcionar información hasta ofrecer servicios especializados, adaptándose a las necesidades de los usuarios.",
    sistemas: "¿Qué es un sistema web?",
    sistemas_subtitle: "Un Sistema Web es una plataforma dinámica y multifacética que va más allá de una simple página web estática. Se trata de una solución digital más robusta, diseñada para ofrecer una experiencia interactiva y funcional a los usuarios. A diferencia de una página de aterrizaje, un Sistema Web cuenta con una estructura más compleja, un flujo de navegación definido y una mayor cantidad de datos e interacciones.",
    crm:"¿Qué es un crm?",
    crmsubtitle:"Un Sistema de Gestión de Relaciones con el Cliente (CRM) es una herramienta digital completa diseñada para administrar las interacciones de una empresa con sus clientes y usuarios. Son una plataforma multifuncional que abarca desde la gestión de clientes y productos hasta la automatización de procesos y el análisis de datos. Esta herramienta permite a las empresas optimizar sus operaciones, mejorar la retención de clientes y aumentar la rentabilidad mediante la organización y seguimiento efectivo de las relaciones comerciales.",
    sucursalchapala: "Terapia Física Personalizada",
    sucursalchapalasubtitle:"La terapia física personalizada es un enfoque integral diseñado para atender las necesidades específicas de cada paciente. A través de una evaluación completa, los fisioterapeutas crean planes de tratamiento ajustados a las condiciones individuales. Estos tratamientos no solo ayudan a recuperarse de lesiones, sino que también mejoran la movilidad, reducen el dolor y fortalecen el cuerpo.",
    sucursalchapaladescription: "En nuestra sucursal de Chapala, nos especializamos en ofrecer terapias físicas personalizadas para ayudarte a recuperar tu bienestar. Nuestro equipo de profesionales está comprometido con tu salud y comodidad.",
    sucursalajijjc: "Sucursal Ajijic",
    sucursalajijicsubtitle: "Ubicada en el pintoresco pueblo de Ajijic, nuestra sucursal combina el encanto del lago con el dulce sabor de nuestros postres. Disfruta de un ambiente relajado y acogedor mientras saboreas nuestras especialidades recién horneadas. ¡Un lugar perfecto para consentirte!",
    sucursaljoco: "Sucursal Jocotepec",
    sucursaljocosubtitle: "En la hermosa región de Jocotepec, nuestra pastelería te ofrece un espacio cálido donde cada bocado es un deleite. Ya sea para un café por la mañana o un pastel para una ocasión especial, aquí encontrarás la combinación perfecta de sabor y calidad. Si necesitas más ajustes o más sucursales, dime y los afinamos.",
    horachapala1: "Lunes - Sábado 9a.m - 9p.m",
    horachapala2: "Domingo 9a.m - 8p.m",
    horajoco1: "Lunes - Sábado 9a.m - 6p.m",
    horajoco2: "Domingo Cerrado",
    horaajijic1: "Lunes - Sábado 8:30a.m - 9p.m",
    horaajijic2: "Domingo 8:30a.m - 7p.m",
    tt_features2: "Progres PT - Servicios y Beneficios",
    stt_features2: "En Progres PT, nos especializamos en ofrecer servicios avanzados de fisioterapia para ayudarte a recuperar tu salud física y mejorar tu calidad de vida. Nuestro equipo profesional utiliza técnicas innovadoras y personalizadas para asegurar tu recuperación completa.",
    dtt_features2: "Fisioterapia Educativa",
    dtt_features2_1: "Proporcionamos información accesible y útil para educar a nuestros pacientes sobre técnicas de recuperación y prevención de lesiones. Diseñado para facilitar tu aprendizaje y comprensión de los tratamientos.",
    dtt_features2_2: "Fotografía Terapéutica",
    dtt_features2_3: "Capturamos momentos clave del proceso de rehabilitación para evaluar progresos y motivar a nuestros pacientes. Ideal para documentar casos de éxito y compartir experiencias.",
    dtt_features2_4: "Atención Profesional",
    dtt_features2_5: "Progres PT brinda un servicio personalizado para cada paciente, ya sea que estés comenzando un proceso de recuperación o buscando mejorar tu calidad de vida.",
    dtt_features2_6: "Identidad de Marca",
    dtt_features2_7: "Nuestra clínica ofrece una imagen coherente y profesional, desde la atención al paciente hasta la comunicación visual de nuestros servicios.",
    dtt_features2_8: "Aplicaciones Médicas",
    dtt_features2_9: "Compartimos herramientas y recursos para profesionales de la salud enfocados en mejorar la comunicación y la calidad de la atención brindada.",
    dtt_features2_10: "Estilo de Vida Saludable",
    dtt_features2_11: "Te brindamos recomendaciones personalizadas para mantener un equilibrio saludable entre la actividad física, la rehabilitación y el bienestar general."

}