export default
 {
    Inicio: "Inicio",
    Productos: "Productos",
    Galeria: "Galeria",
    Sucursales: "Sucursales",
    pasteles: "Pasteles",
    Muffins: "Muffins",
    Galletas: "Galletas",
    Contactanos: "Contáctanos",
    buscas: "¿Buscas el pastel perfecto o un postre delicioso?",
    buscas1: "Con nuestro proceso sencillo y personalizado, puedes encargar tus postres favoritos en pocos pasos. Descubre cómo hacerlo y disfruta de una experiencia dulce y sin complicaciones.",
    INICIO1: "Pastelería América es un negocio especializado en la creación de postres y pasteles artesanales, caracterizado por su calidad, tradición y estilo elegante. Ofrece una variedad de opciones dulces, ideales para celebraciones y momentos especiales, destacándose por su atención al detalle y sabores exquisitos.",
    paso1: "Explora nuestro menú",
    DESCRIPTION1: "Revisa nuestra variedad de productos: pasteles personalizados, postres individuales, y más. Encuentra inspiración en nuestra galería de sabores y decoraciones.",
    paso2: "Contáctanos o realiza tu pedido en línea",
    DESCRIPTION2: "Haz tu pedido directamente desde nuestra tienda en línea o contáctanos para consultas y personalizaciones. Nos encanta hacer realidad tus ideas dulces.",
    paso3: "Personaliza tu elección",
    DESCRIPTION3: "Selecciona sabores, tamaños y decoraciones especiales para hacer tu pastel único. Nuestros expertos en repostería te ayudarán a lograrlo.",
    paso4: "Recoge o recibe tu pedido",
    DESCRIPTION4: "Pasa por nuestra tienda para recoger tu pedido o aprovecha nuestro servicio de entrega a domicilio.",
    unico: "Lo que nos hace únicos",
    WID1: "Sabores únicos y de alta calidad",
    WID_1: "Usamos ingredientes frescos y seleccionados cuidadosamente para garantizar el mejor sabor en cada bocado.",
    WID2: "Diseños personalizados",
    WID_2: "Ofrecemos pasteles y postres con decoraciones únicas adaptadas a tus gustos y ocasiones especiales.",
    WID3: "Atención al detalle",
    WID_3: "Cada creación es elaborada artesanalmente, asegurándonos de cumplir con tus expectativas.",
    WID4: "Entrega confiable",
    WID_4: "Recibe tus pedidos a tiempo con nuestro servicio de entrega a domicilio, perfecto para eventos importantes.",
    visit: "Visítanos",
    testimonials: "Testimonios",
    testimonios1: "Riquísimos los pasteles hechos con amor! Desde la envoltura y la atención y todo, no se diga de las gelatinas súper ricas al momento de disfrutarlas saben a su sabor y no tan dulces! Me encanta pastelería america por su rico sabor Casero, y se con el cariño y amor q los preparan y eso se sabe! 💕🤗🌟✨💕",
    testimonios2: "Excelente calidad de pasteles y un sabor único.",
    testimonios3: "Excelente servicio, muy buena calidad, super deliciosos, demasiado creativos, muy profesionales y super amables! Me encantan sus pasteles, todos son super deliciosos! 🤤 Super recomendado! 🤗 ",
    testimonios4: "Excelente servicio sabor calidad en decoración ni se diga hermosos pasteles una repostería rica!!! ",
    testimonios5: "Excelente pasteleria, la mejor en Ribera de Chapala. No vayas a ningún otro lado.",
    testimonios6: "Los pasteles están deliciosos y tienen gran variedad de producto y las decoraciones son muy bonitas ",
    FAQS: "Preguntas Frecuentes",
    faqs1: "¿Puedo personalizar mi pastel o postre?",
    faqs_1: "¡Sí, definitivamente! Puedes personalizar tu pastel o postre con nombres, colores, temas específicos e incluso sabores únicos. Solo asegúrate de informarnos sobre tus preferencias al hacer el pedido, y nos encargaremos de hacer que tu diseño sea perfecto.",
    faqs2: "¿Con cuánta anticipación debo hacer mi pedido?",
    faqs_2: "Para eventos especiales como cumpleaños o bodas, recomendamos hacer tu pedido con al menos 3 a 5 días de anticipación. Si se trata de un pedido más grande o con decoraciones complejas, es ideal hacerlo con una semana de antelación. ¡Cuanto antes, mejor para asegurarte de que tengamos disponibilidad!",
    faqs3: "¿Tienen opciones para personas con restricciones alimenticias?",
    faqs_3: "Sí, ofrecemos opciones para personas con diversas restricciones alimenticias. Tenemos pasteles sin gluten, sin azúcar, veganos y sin lácteos. Por favor, indícanos cualquier restricción al realizar tu pedido y nos aseguraremos de ofrecerte una opción deliciosa y segura.",
    faqs4: "¿Ofrecen servicio de entrega a domicilio?",
    faqs_4: "Sí, ofrecemos servicio de entrega a domicilio. Puedes optar por esta opción al hacer tu pedido, y nos aseguraremos de que tu pastel o postre llegue a tiempo y en perfecto estado, directamente a la ubicación que elijas.",
    faqs5: "¿Cuáles son los sabores y tamaños disponibles?",
    faqs_5: "Tenemos una variedad de sabores para elegir, incluyendo vainilla, chocolate, red velvet, frutas y más. Además, ofrecemos diferentes tamaños de pasteles según tus necesidades, desde pequeños para reuniones familiares hasta grandes para eventos. ¡No dudes en preguntar por nuestras opciones y nos aseguraremos de que encuentres la perfecta para tu ocasión!",
    faqs6: "¿Cuánto tiempo duran los pasteles y cómo debo almacenarlos?",
    faqs_6: "Nuestros pasteles se mantienen frescos hasta 3 días si se conservan en un lugar fresco y seco. Si tienen rellenos o crema, recomendamos guardarlos en el refrigerador y sacarlos 30 minutos antes de servir para disfrutar su mejor sabor y textura.",
    PASTELES: "Pasteles",
    PASTELES0: "Descubre nuestros pasteles más deliciosos y populares, ideales para cualquier ocasión.",
    PASTEL1: "Pastel de Tres Leches Vainilla",
    PASTEL_1: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__1: "Pan de vainilla relleno de crema y mermelada de fresa bañado en leche.",
    PASTEL_2: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__2: "Bizcocho esponjoso infusionado con café, bañado en tres leches sabor capuccino y relleno de crema de mantequilla con un toque de caramelo y trozos de nuez.",
    PASTEL3: "Pastel Red Velvet",
    PASTEL_3: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__3: "Pan de chocolate rojo con relleno de crema de queso.",
    PASTEL4: "Pastel de Zanahoria con crema de Queso",
    PASTEL_4: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__4: "Pan de zanahoria con nuez, piña y arandanos, libre de huevo",
    PASTEL___4: "Relleno de crema de queso.",
    PASTEL5: "Oreo",
    PASTEL_5: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__5: "Pan de chocolate semi amargo relleno con crema sabor a oreo y galleta.",
    PASTEL6: "Moka",
    PASTEL_6: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__6: "Pan de vainilla bañado en licor de café, relleno de crema de mantequilla y nuez.",
    PASTEL7: "Chocoqueso",
    PASTEL_7: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__7: "Pan de chocolate americano. Suave con relleno de flan de queso.",
    PASTEL8: "Doble Chocolate",
    PASTEL_8: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__8: "Pan de chocolate semi amargo, bañado en Jarabe.",
    PASTEL___8: "Relleno en crema de chocolate, cubierto con ganashe al 60% de cacao.",
    PASTEL9: "Doble Chocolate con Fruta",
    PASTEL_9: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__9: "Delicioso bizcocho de chocolate con un cremoso relleno de cheesecake, logrando un balance perfecto entre dulzura e intensidad.",
    PASTEL10: "Pastel de Naranja",
    PASTEL_10: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__10: "Pan suave de naranja con rayadura natural, relleno de crema de naranja y queso.",
    PASTEL11: "Chocoflan",
    PASTEL_11: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__11: "Capas de suave flan de vainilla y bizcocho de chocolate en una sola preparación.",
    PASTEL___11: "Bañado en caramelo dorado para un sabor dulce y equilibrado.",
    PASTEL____11: "Textura cremosa y esponjosa en cada bocado.",
    PASTEL12: "Pastel de Zanahoria",
    PASTEL_12: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__12: "Pan de zanahoria con nuez, piña y arandano y libre de huevo.",
    PASTEL___12: "Relleno con crema de nata.",
    PASTEL13: "Chocovainilla",
    PASTEL_13: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__13: "Mitad de doble chocolate y mitad de pan de vainilla.",
    PASTEL___13: "Relleno de crema y fruta (durazno, fresa y nuez).",
    PASTEL14: "Mil Hojas",
    PASTEL_14: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__14: "Capas de pan de hojaldre, relleno con crema pastelera, durazno, fresa y nuez.",
    PASTEL___14: "Cubierto con crema de limón.",
    PASTEL15: "Marmoleado",
    PASTEL_15: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__15: "Pan de vainilla con chocolate americano extra suave.",
    PASTEL___15: "Con una capa rellena de crema de nata, durazno y nuez.",
    PASTEL____15: "Con una capa de relleno de crema de chocolate.",
    PASTEL16: "Pastel de Frutas",
    PASTEL_16: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__16: "Pastel de vainilla, relleno de frutas /durazno, piña, fresa y nuez).",
    PASTEL___16: "Bañado en Jarabe.",
    PASTEL17: "Cheesecake",
    PASTEL_17: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__17: "Delicioso bizcocho de chocolate con un cremoso relleno de cheesecake, logrando un balance perfecto entre dulzura e intensidad.",
    PASTEL18: "Pastel de Nuez",
    PASTEL_18: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__18: "Pan sabor a nuez, con relleno de crema y trozos de nuez.",
    PASTEL19: "Selva Negra",
    PASTEL_19: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__19: "Pan de chocolate amargo, con relleno de crema y cereza.",
    PASTEL20: "Pastel de Tres Leches Chocolate",
    PASTEL_20: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__20: "Pan de chocolate bañado en 3 leches, con relleno de crema de chocolate.",
    PASTEL21: "Pastel de Dulce de Leche",
    PASTEL_21: "Pastel Chico (5 personas - $200), Pastel Mediano (10 personas - $300).",
    PASTEL__21: "Pan sabor a tres leches, con dulce de leche, en la leche y en el relleno.",
    galeriade: "Galería de Postres",
    galeriades: "Deliciosos postres para cada ocasión",
    nuestros_videos: "Nuestros Videos",
    explora: "Explora más con nosotros.",
    videotitle1: "Técnicas",
    videodes1: "Técnica en decoracion con duyas o boquillas.",
    videotitle2: "Así nacen nuestros pasteles",
    videodes2: "El arte detrás de cada bocado.",
    videotitle3: "Pastel y café: una dulce visita",
    videodes3:"Sabor y momentos inolvidables.",
    blog1: "Bienvenido a Nuestro Blogs de Pastelería",
    blog: "Si eres amante de la repostería, este es el lugar perfecto para ti. En nuestro blog encontrarás recetas deliciosas, técnicas de horneado, trucos para decorar pasteles y errores comunes que debes evitar. Ya seas un principiante que quiere aprender a hacer su primer bizcocho o un experto en busca de inspiración, aquí descubrirás todo lo que necesitas para mejorar tus habilidades en la cocina.",
    publicaciones: "Publicaciones Relacionadas",
    todaspublicaciones: "Ver Todas las Publicaciones ",
    horario: "Horario",
    ubicacion: "Ubicación",
    pedidos: "Conéctate con nosotros",
    pedidos1: "Para pedidos, cotizaciones o cualquier consulta, estamos a un clic de distancia.",
    sucursalchapala: "Sucursal Chapala",
    sucursalchapalasubtitle: "Ubicada en el corazón de Chapala, nuestra sucursal ofrece un ambiente acogedor donde podrás disfrutar de nuestros exquisitos pasteles y postres artesanales. Con una vista increíble y un espacio cómodo, es el lugar ideal para compartir momentos dulces con tus seres queridos.",
    sucursalajijjc: "Sucursal Ajijic",
    sucursalajijicsubtitle: "Ubicada en el pintoresco pueblo de Ajijic, nuestra sucursal combina el encanto del lago con el dulce sabor de nuestros postres. Disfruta de un ambiente relajado y acogedor mientras saboreas nuestras especialidades recién horneadas. ¡Un lugar perfecto para consentirte!",
    sucursaljoco: "Sucursal Jocotepec",
    sucursaljocosubtitle: "En la hermosa región de Jocotepec, nuestra pastelería te ofrece un espacio cálido donde cada bocado es un deleite. Ya sea para un café por la mañana o un pastel para una ocasión especial, aquí encontrarás la combinación perfecta de sabor y calidad. Si necesitas más ajustes o más sucursales, dime y los afinamos.",
    horachapala1: "Lunes - Sábado 9a.m - 9p.m",
    horachapala2: "Domingo 9a.m - 8p.m",
    horajoco1: "Lunes - Sábado 9a.m - 6p.m",
    horajoco2: "Domingo Cerrado",
    horaajijic1: "Lunes - Sábado 8:30a.m - 9p.m",
    horaajijic2: "Domingo 8:30a.m - 7p.m"
    
}